discutea_tutorial_tutorial_routing:
    resource: "@DTutoBundle/Controller/TutorialController.php"
    prefix:   /
    type:     annotation

discutea_tutorial_category_routing:
    resource: "@DTutoBundle/Controller/CategoryController.php"
    prefix:   /
    type:     annotation

discutea_tutorial_admin_routing:
    resource: "@DTutoBundle/Controller/AdminController.php"
    prefix:   /
    type:     annotation

discutea_tutorial_contribution_routing:
    resource: "@DTutoBundle/Controller/ContributionController.php"
    prefix:   /
    type:     annotation
