services:
    discutea.security.tutorial_voter:
        class: Discutea\DTutoBundle\Security\TutorialVoter
        arguments: 
            - '@security.access.decision_manager'
        public: false
        tags:
            - { name: security.voter }

    DTutoBundle.twig_extension:
        class: Discutea\DTutoBundle\Twig\DTutoExtension
        arguments: 
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
        public: false
        tags:
            - { name: twig.extension }
