services:
    discutea.security.tutorial_voter:
        class: Discutea\DTutoBundle\Security\TutorialVoter
        arguments: 
            - '@security.access.decision_manager'
        public: false
        tags:
            - { name: security.voter }

    discutea.security.contribution_voter:
        class: Discutea\DTutoBundle\Security\ContributionVoter
        arguments: 
            - '@security.access.decision_manager'
        public: false
        tags:
            - { name: security.voter }

    DTutoBundle.twig_extension:
        class: Discutea\DTutoBundle\Twig\DTutoExtension
        arguments: 
            - '@doctrine.orm.entity_manager'
        public: false
        tags:
            - { name: twig.extension }

    discutea.form.type.contribution:
        class: Discutea\DTutoBundle\Form\Type\ContributionType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type }
